version: '3.6'
services:
  node:
   image: node
   command: tail -f /dev/null
   volumes:
     - internal-vol:/shared
  nginx:
   image: nginx
   volumes:
     - internal-vol:/home/app/shared

volumes:
  internal-vol: